Repository validator-labs/validator-plugin-network, pull requests merged in 2024-07, with the labels that each got.

#219 chore: fix typos in README
  README.md
Labels: documentation, size:XS, lgtm

#205 chore(main): release 0.0.18
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-network/Chart.yaml
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: autorelease: pending, size:M

#222 chore(main): release 0.0.18
  CHANGELOG.md
Labels: bug, enhancement, autorelease: pending, size:L

#225 feat: enhance tcp conn rules
  Dockerfile
  Dockerfile.devspace
  Makefile
  api/v1alpha1/networkvalidator_types.go
  config/crd/bases/validation.spectrocloud.labs_networkvalidators.yaml
  config/samples/networkvalidator-networkrules.yaml
  internal/controller/networkvalidator_controller.go
  internal/http/http.go
  internal/validators/network.go
  internal/validators/network_test.go
Labels: enhancement, size:L, lgtm

#230 fix: update chart crd
  chart/validator-plugin-network/crds/validation.spectrocloud.labs_networkvalidators.yaml
Labels: bug, size:S, lgtm

#227 chore(main): release 0.0.20
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-network/Chart.yaml
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: autorelease: pending, size:S, lgtm

#232 chore(main): release 0.0.21
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-network/Chart.yaml
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: autorelease: pending, size:S
