Repository validator-labs/validator-plugin-network, pull requests merged in 2024-12, with the labels that each got.

#301 chore: re-scaffold project
  .golangci.yml
  api/v1alpha1/networkvalidator_types.go
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/templates/deployment.yaml
  chart/validator-plugin-network/templates/manager-rbac.yaml
  chart/validator-plugin-network/templates/metrics-auth-rbac.yaml
  chart/validator-plugin-network/templates/metrics-reader-rbac.yaml
  chart/validator-plugin-network/templates/metrics-service.yaml
  chart/validator-plugin-network/values.yaml
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_metrics_patch.yaml
  config/default/metrics_service.yaml
  config/manager/manager.yaml
  config/network-policy/allow-metrics-traffic.yaml
  config/network-policy/kustomization.yaml
  config/rbac/kustomization.yaml
  config/rbac/metrics_auth_role.yaml
  config/rbac/metrics_auth_role_binding.yaml
  config/rbac/metrics_reader_role.yaml
  config/samples/kustomization.yaml
  go.mod
  go.sum
  internal/controller/networkvalidator_controller.go
  internal/controller/networkvalidator_controller_test.go
  internal/controller/suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/e2e_test.go
  tests/utils/utils.go
Labels: enhancement, size:XXL

#272 chore(main): release 0.1.1
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-network/Chart.yaml
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: autorelease: pending, size:M, lgtm

#308 fix: metrics targetPort https -> 8443
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: size:XS, lgtm

#305 chore(main): release 0.1.2
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-network/Chart.yaml
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: autorelease: pending, size:S
