Repository validator-labs/validator-plugin-network, pull requests merged in 2024-08, with the labels that each got.

#239 refactor: support direct rule evaluation
  api/v1alpha1/networkvalidator_types.go
  go.mod
  go.sum
  internal/controller/networkvalidator_controller.go
  internal/controller/networkvalidator_controller_test.go
  pkg/constants/constants.go
  pkg/http/http.go
  pkg/http/http_test.go
  pkg/network/network.go
  pkg/network/network_test.go
  pkg/secrets/secrets.go
  pkg/secrets/secrets_test.go
  pkg/validate/validate.go
Labels: enhancement, size:L

#237 chore(main): release 0.0.22
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-network/Chart.yaml
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: autorelease: pending, size:S

#242 chore: fix 'publicly accessible' wording
  README.md
  api/v1alpha1/networkvalidator_types.go
  chart/validator-plugin-network/crds/validation.spectrocloud.labs_networkvalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_networkvalidators.yaml
  pkg/network/network.go
  pkg/network/network_test.go
  pkg/secrets/secrets.go
Labels: documentation, size:M

#246 chore: satisfy ValidationRule
  api/v1alpha1/networkvalidator_types.go
  go.mod
  go.sum
Labels: size:S

#243 chore(main): release 0.0.23
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-network/Chart.yaml
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: documentation, autorelease: pending, size:S, lgtm

#258 refactor: make each rule implement `validationrule.Interface`
  api/v1alpha1/networkvalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/controller/networkvalidator_controller.go
  pkg/network/network.go
Labels: enhancement, size:M, lgtm

#253 chore(main): release 0.0.24
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-network/Chart.yaml
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: autorelease: pending, size:S

#261 fix: embedding structs related to `validationrule.Interface`
  api/v1alpha1/networkvalidator_types.go
Labels: bug, size:S

#259 chore: assert that PluginSpec is implemented
  api/v1alpha1/networkvalidator_types.go
  go.mod
  go.sum
Labels: size:XS, lgtm

#262 chore(main): release 0.0.25
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-network/Chart.yaml
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: bug, autorelease: pending, size:S

#265 fix: YAML rendering of structs embedded in rules
  api/v1alpha1/networkvalidator_types.go
Labels: bug, size:S

#266 chore(main): release 0.0.26
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-network/Chart.yaml
  chart/validator-plugin-network/README.md
  chart/validator-plugin-network/values.yaml
Labels: bug, autorelease: pending, size:S
